const recipes = [
  // PETIT-DÉJEUNER
  { id: 1, name: "Porridge aux fruits rouges", cat: "Petit-déjeuner", time: "10 min", img: "oatmeal,breakfast", ingredients: [["Flocons d'avoine", "80g", 0.30], ["Lait demi-écrémé", "200ml", 0.22], ["Fruits rouges surgelés", "80g", 0.60], ["Miel", "1 c.à.s", 0.15]], instructions: "Faire chauffer le lait, ajouter les flocons d'avoine et cuire 5 min en remuant. Ajouter les fruits rouges et le miel.", desc: "Bol chaud, rassasiant et plein d'antioxydants." },
  { id: 2, name: "Toast avocat œuf poché", cat: "Petit-déjeuner", time: "15 min", img: "avocado,toast", ingredients: [["Pain de campagne", "2 tranches", 0.40], ["Avocat", "1", 1.20], ["Œufs", "2", 0.60], ["Citron", "1/2", 0.25], ["Piment d'Espelette", "pincée", 0.05]], instructions: "Pocher les œufs 3 min dans eau vinaigrée. Écraser l'avocat avec citron. Toaster le pain. Assembler.", desc: "Le brunch iconique, fait maison et pas cher." },
  { id: 3, name: "Crêpes au sarrasin jambon fromage", cat: "Petit-déjeuner", time: "20 min", img: "crepe,buckwheat", ingredients: [["Farine de sarrasin", "150g", 0.45], ["Eau", "250ml", 0], ["Jambon", "2 tranches", 2.2], ["Fromage râpé", "50g", 2.3], ["Beurre", "20g", 0.10]], instructions: "Mélanger farine et eau pour la pâte. Cuire les galettes. Garnir jambon-fromage et plier.", desc: "Galette bretonne classique, repas complet à budget mini." },
  { id: 4, name: "Yaourt granola maison", cat: "Petit-déjeuner", time: "5 min", img: "yogurt,granola", ingredients: [["Yaourt grec", "2", 0.80], ["Granola", "60g", 0.50], ["Banane", "1", 0.30], ["Miel", "1 c.à.s", 0.15]], instructions: "Verser le yaourt dans un bol. Ajouter le granola et la banane en rondelles. Arroser de miel.", desc: "Rapide, nourrissant, délicieux." },
  { id: 5, name: "Œufs brouillés champignons", cat: "Petit-déjeuner", time: "10 min", img: "scrambled,eggs,mushrooms", ingredients: [["Œufs", "3", 0.90], ["Champignons de Paris", "100g", 0.80], ["Beurre", "15g", 0.08], ["Ciboulette", "qq tiges", 0.20], ["Sel, poivre", "", 0.02]], instructions: "Faire revenir les champignons au beurre. Battre les œufs, cuire à feu doux en remuant. Assaisonner.", desc: "Protéiné et savoureux pour bien démarrer." },

  // ENTRÉES
  { id: 6, name: "Soupe à l'oignon gratinée", cat: "Entrée", time: "45 min", img: "onion,soup,gratinated", ingredients: [["Oignons", "4", 1.20], ["Bouillon de bœuf", "1L", 0.60], ["Baguette", "4 tranches", 0.40], ["Gruyère râpé", "80g", 2.3], ["Beurre", "30g", 0.15]], instructions: "Caraméliser les oignons 30 min au beurre. Ajouter le bouillon, mijoter 10 min. Verser en ramequins, poser le pain + gruyère. Gratiner au four.", desc: "Classique bistrot, réconfortant et economique." },
  { id: 8, name: "Velouté de butternut", cat: "Entrée", time: "30 min", img: "butternut,soup,cream", ingredients: [["Butternut", "800g", 1.60], ["Oignon", "1", 0.20], ["Crème fraîche", "100ml", 1.2], ["Bouillon légumes", "500ml", 0.30], ["Noix de muscade", "pincée", 0.05]], instructions: "Cuire butternut et oignon dans le bouillon 20 min. Mixer. Ajouter crème, sel, muscade.", desc: "Doux, soyeux, parfait en automne." },
  { id: 10, name: "Bruschetta tomate basilic", cat: "Entrée", time: "10 min", img: "bruschetta,tomato,basil", ingredients: [["Baguette", "6 tranches", 0.60], ["Tomates", "3", 1.20], ["Basilic frais", "10 feuilles", 0.40], ["Ail", "1 gousse", 0.10], ["Huile d'olive", "3 c.à.s", 0.30]], instructions: "Toaster le pain, frotter ail. Couper tomates en dés, mélanger basilic et huile. Déposer sur le pain.", desc: "L'apéro italien rapide et frais." },
  { id: 11, name: "Gaspacho andalou", cat: "Entrée", time: "15 min", img: "gazpacho,cold,soup", ingredients: [["Tomates mûres", "600g", 1.80], ["Concombre", "1", 0.50], ["Poivron rouge", "1", 0.80], ["Ail", "1 gousse", 0.10], ["Pain rassis", "60g", 0.15], ["Huile d'olive", "3 c.à.s", 0.30]], instructions: "Mixer tous les légumes avec pain, huile, sel et vinaigre. Réfrigérer 1h minimum.", desc: "Soupe froide espagnole, parfaite l'été." },
  { id: 12, name: "Salade de lentilles vinaigrette", cat: "Entrée", time: "25 min", img: "lentil,salad,french", ingredients: [["Lentilles vertes", "200g", 0.70], ["Carottes", "2", 0.40], ["Oignon rouge", "1", 0.30], ["Persil", "1 bouquet", 0.50], ["Moutarde", "1 c.à.c", 0.10], ["Huile d'olive", "3 c.à.s", 0.30]], instructions: "Cuire les lentilles 20 min. Égoutter. Mélanger avec carottes râpées, oignon émincé, vinaigrette moutardée.", desc: "Riche en protéines, économique et délicieux." },

  // PLATS PRINCIPAUX - VIANDE
  { id: 13, name: "Poulet rôti pommes de terre", cat: "Plat", time: "1h15", img: "roast,chicken,potatoes", ingredients: [["Poulet entier", "1.4kg", 7.00], ["Pommes de terre", "600g", 1.20], ["Ail", "4 gousses", 0.30], ["Romarin", "2 branches", 0.30], ["Beurre", "40g", 0.20], ["Citron", "1", 0.40]], instructions: "Beurrer le poulet, fourrer de citron et ail. Enfourner 1h15 à 200°C avec les pommes de terre.", desc: "Le classique du dimanche, savoureux et rassasiant." },
  { id: 14, name: "Bœuf bourguignon", cat: "Plat", time: "2h30", img: "beef,bourguignon,stew", ingredients: [["Bœuf à braiser", "600g", 8.40], ["Vin rouge", "400ml", 1.60], ["Carottes", "3", 0.60], ["Oignons grelots", "150g", 0.90], ["Champignons", "200g", 1.60], ["Lardons", "100g", 2]], instructions: "Faire revenir le bœuf en morceaux. Ajouter vin, légumes. Mijoter 2h à feu doux.", desc: "Le grand classique bourguignon, mijoté avec amour." },
  { id: 15, name: "Hachis Parmentier", cat: "Plat", time: "45 min", img: "hachis,parmentier,mashed,potato", ingredients: [["Viande hachée bœuf", "400g", 4.40], ["Pommes de terre", "800g", 1.60], ["Oignon", "1", 0.20], ["Lait", "100ml", 0.11], ["Beurre", "40g", 0.20], ["Gruyère", "80g", 2.30]], instructions: "Cuire viande hachée avec oignon. Faire la purée. Alterner couches viande/purée. Gratiner.", desc: "Comfort food française par excellence." },
  { id: 16, name: "Escalope de veau à la crème", cat: "Plat", time: "20 min", img: "veal,escalope,cream,sauce", ingredients: [["Escalopes de veau", "2 × 130g", 8.00], ["Crème fraîche", "150ml", 1.2], ["Champignons", "150g", 1.20], ["Echalotes", "2", 0.30], ["Beurre", "25g", 0.13]], instructions: "Cuire les escalopes au beurre. Faire revenir échalotes et champignons. Déglacer crème. Napper.", desc: "Élégance française en 20 minutes." },
  { id: 17, name: "Côtes de porc moutarde", cat: "Plat", time: "25 min", img: "pork,chops,mustard,sauce", ingredients: [["Côtes de porc", "2", 3.60], ["Moutarde de Dijon", "2 c.à.s", 0.25], ["Crème fraîche", "100ml", 1.2], ["Herbes de Provence", "1 c.à.c", 0.05], ["Huile d'olive", "2 c.à.s", 0.20]], instructions: "Badigeonner les côtes de moutarde. Faire dorer 5 min chaque côté. Déglacer à la crème.", desc: "Rapide et savoureux, parfait en semaine." },
  { id: 18, name: "Poulet au curry et lait de coco", cat: "Plat", time: "35 min", img: "chicken,curry,coconut,milk", ingredients: [["Blanc de poulet", "400g", 5.20], ["Lait de coco", "400ml", 1.60], ["Curry en poudre", "2 c.à.s", 0.20], ["Oignon", "1", 0.20], ["Tomates", "2", 0.80], ["Riz basmati", "200g", 0.60]], instructions: "Faire revenir oignon et poulet. Ajouter curry, tomates, lait de coco. Mijoter 20 min. Servir avec riz.", desc: "Exotique, doux et parfumé." },
  { id: 19, name: "Blanquette de veau", cat: "Plat", time: "1h30", img: "blanquette,veal,white,sauce", ingredients: [["Veau à braiser", "600g", 12.00], ["Carottes", "3", 0.60], ["Oignons", "2", 0.40], ["Crème fraîche", "200ml", 1.2], ["Champignons", "150g", 1.20], ["Jaunes d'œufs", "2", 0.60]], instructions: "Cuire veau dans bouillon avec légumes 1h. Lier la sauce crème + jaunes. Ajouter champignons.", desc: "La blanquette de mamie, crémeuse et tendre." },
  { id: 20, name: "Boulettes de viande sauce tomate", cat: "Plat", time: "40 min", img: "meatballs,tomato,sauce,pasta", ingredients: [["Viande hachée mixte", "400g", 4.00], ["Tomates pelées en boîte", "400g", 0.90], ["Oignon", "1", 0.20], ["Ail", "2 gousses", 0.15], ["Chapelure", "40g", 0.15], ["Pâtes", "300g", 0.75]], instructions: "Former les boulettes avec viande, chapelure, sel. Dorer puis mijoter dans sauce tomate 20 min. Servir avec pâtes.", desc: "Les enfants adorent, les adultes aussi." },

  // PLATS - POISSON

  // PLATS VÉGÉTARIENS
  { id: 26, name: "Ratatouille provençale", cat: "Plat végétarien", time: "1h", img: "ratatouille,provencal,vegetables", ingredients: [["Courgettes", "3", 1.50], ["Aubergines", "2", 1.60], ["Poivrons", "2", 1.60], ["Tomates", "4", 1.60], ["Oignon", "1", 0.20], ["Ail", "3 gousses", 0.20]], instructions: "Couper tous les légumes. Faire revenir oignon et ail. Ajouter légumes par ordre de cuisson. Mijoter 40 min.", desc: "Le grand plat du soleil, savoureux et coloré." },
  { id: 27, name: "Quiche lorraine", cat: "Plat végétarien", time: "45 min", img: "quiche,lorraine,eggs", ingredients: [["Pâte brisée", "1 rouleau", 2], ["Œufs", "3", 0.90], ["Crème fraîche", "200ml", 1.2], ["Lardons", "150g", 2], ["Gruyère râpé", "100g", 2.3], ["Lait", "100ml", 0.11]], instructions: "Foncer la pâte. Mélanger œufs, crème, lait. Ajouter lardons et gruyère. Cuire 35 min à 180°C.", desc: "La quiche classique, inratable et appréciée." },
  { id: 28, name: "Gratin dauphinois", cat: "Plat végétarien", time: "1h15", img: "potato,gratin,dauphinois,cream", ingredients: [["Pommes de terre", "1kg", 2.00], ["Crème fraîche", "300ml", 1.2], ["Lait", "200ml", 0.22], ["Ail", "2 gousses", 0.15], ["Noix de muscade", "pincée", 0.05]], instructions: "Couper pommes de terre fines. Frotter plat d'ail. Alterner couches. Verser mélange crème-lait. Cuire 1h à 170°C.", desc: "Onctueux et réconfortant, accompagnement parfait." },
  { id: 29, name: "Curry de pois chiches épinards", cat: "Plat végétarien", time: "25 min", img: "chickpea,curry,spinach", ingredients: [["Pois chiches en boîte", "400g", 0.90], ["Épinards", "200g", 1.00], ["Lait de coco", "200ml", 0.80], ["Oignon", "1", 0.20], ["Curry", "2 c.à.s", 0.20], ["Gingembre", "1 c.à.c", 0.10]], instructions: "Faire revenir oignon, ajouter curry et gingembre. Ajouter pois chiches, lait de coco. Cuire 10 min. Incorporer épinards.", desc: "Vegan, rapide, savoureux et rassasiant." },
  { id: 30, name: "Tian de légumes", cat: "Plat végétarien", time: "1h", img: "tian,vegetables,provencal", ingredients: [["Courgettes", "2", 1.00], ["Tomates", "3", 1.20], ["Aubergines", "1", 0.80], ["Oignon", "1", 0.20], ["Herbes Provence", "1 c.à.s", 0.10], ["Huile d'olive", "3 c.à.s", 0.30]], instructions: "Couper tous les légumes en rondelles. Alterner dans plat huilé. Parsemer herbes. Cuire 50 min à 180°C.", desc: "Beau à voir, léger et méditerranéen." },
  { id: 31, name: "Pasta primavera", cat: "Plat végétarien", time: "20 min", img: "pasta,spring,vegetables,primavera", ingredients: [["Pâtes", "300g", 0.75], ["Petits pois", "150g", 0.70], ["Asperges", "150g", 1.80], ["Parmesan", "50g", 1.00], ["Crème fraîche", "100ml", 1.2], ["Basilic", "10 feuilles", 0.30]], instructions: "Cuire pâtes. Faire sauter légumes. Mélanger pâtes, légumes, crème. Parsemer parmesan et basilic.", desc: "Fraîcheur printanière dans l'assiette." },
  { id: 32, name: "Risotto aux champignons", cat: "Plat végétarien", time: "35 min", img: "risotto,mushrooms,parmesan", ingredients: [["Riz Arborio", "300g", 1.20], ["Champignons de Paris", "250g", 2.00], ["Oignon", "1", 0.20], ["Vin blanc", "150ml", 0.60], ["Bouillon légumes", "1L", 0.60], ["Parmesan", "60g", 1.20]], instructions: "Faire revenir oignon et champignons. Ajouter riz, mouiller au vin puis bouillon louche par louche. Mantecatura avec parmesan.", desc: "Le risotto parfait, crémeux et savoureux." },
  { id: 33, name: "Omelette aux fines herbes", cat: "Plat végétarien", time: "10 min", img: "omelette,herbs,french", ingredients: [["Œufs", "3", 0.90], ["Ciboulette", "qq tiges", 0.20], ["Persil", "qq feuilles", 0.10], ["Cerfeuil", "qq feuilles", 0.10], ["Beurre", "15g", 0.08]], instructions: "Battre les œufs avec herbes. Faire fondre beurre à feu vif. Verser, plier l'omelette baveuse.", desc: "L'omelette classique, simple et parfaite." },
  { id: 34, name: "Soupe minestrone", cat: "Plat végétarien", time: "40 min", img: "minestrone,soup,vegetables,beans", ingredients: [["Haricots blancs boîte", "400g", 0.90], ["Tomates pelées boîte", "400g", 0.90], ["Courgettes", "2", 1.00], ["Carottes", "2", 0.40], ["Céleri", "2 branches", 0.40], ["Petites pâtes", "80g", 0.25]], instructions: "Faire revenir légumes. Ajouter tomates et bouillon. Cuire 20 min. Ajouter haricots et pâtes. Cuire encore 10 min.", desc: "Soupe-repas italienne, nourrissante et économique." },
  { id: 35, name: "Buddha bowl quinoa légumes", cat: "Plat végétarien", time: "30 min", img: "buddha,bowl,quinoa,vegetables", ingredients: [["Quinoa", "200g", 1.40], ["Avocat", "1", 1.20], ["Carottes", "2", 0.40], ["Concombre", "1/2", 0.30], ["Edamame", "100g", 1.00], ["Sauce tahini", "2 c.à.s", 0.40]], instructions: "Cuire quinoa. Assembler dans bol avec légumes crus et avocat. Napper sauce tahini.", desc: "Complet, coloré, sain et rassasiant." },

  // PLATS - PÂTES & RIZ
  { id: 36, name: "Spaghetti carbonara", cat: "Plat", time: "20 min", img: "spaghetti,carbonara,italian", ingredients: [["Spaghetti", "300g", 0.75], ["Lardons fumés", "150g", 2], ["Parmesan", "60g", 1.20], ["Œufs entiers", "2", 0.60], ["Jaunes d'œufs", "2", 0.60]], instructions: "Cuire pâtes al dente. Battre œufs + parmesan. Faire revenir lardons. Mélanger hors feu pâtes, lardons, œufs.", desc: "La vraie carbonara romaine, sans crème." },
  { id: 37, name: "Lasagnes bolognaise", cat: "Plat", time: "1h30", img: "lasagna,bolognese,baked", ingredients: [["Plaques de lasagnes", "12", 1.20], ["Viande hachée", "500g", 5.50], ["Tomates concassées boîte", "800g", 1.80], ["Béchamel", "500ml", 0.80], ["Parmesan", "80g", 1.60], ["Oignon", "1", 0.20]], instructions: "Préparer bolognaise. Alterner couches lasagnes/bolognaise/béchamel. Terminer parmesan. Cuire 45 min à 180°C.", desc: "Les lasagnes comme en Italie, fondantes et dorées." },
  { id: 38, name: "Penne all'arrabbiata", cat: "Plat", time: "20 min", img: "penne,arrabbiata,spicy,tomato", ingredients: [["Penne", "300g", 0.75], ["Tomates pelées boîte", "400g", 0.90], ["Ail", "3 gousses", 0.20], ["Piment rouge", "1", 0.30], ["Huile d'olive", "3 c.à.s", 0.30], ["Parmesan", "40g", 0.80]], instructions: "Faire revenir ail et piment. Ajouter tomates, cuire 15 min. Mélanger avec pâtes al dente.", desc: "Pimentée et rapide, la pasta de l'impatient." },
  { id: 39, name: "Riz cantonnais", cat: "Plat", time: "20 min", img: "fried,rice,cantonese,egg", ingredients: [["Riz cuit", "400g", 0.60], ["Œufs", "2", 0.60], ["Petits pois", "100g", 0.50], ["Carottes", "1", 0.20], ["Sauce soja", "2 c.à.s", 0.15], ["Jambon", "100g", 2.2]], instructions: "Faire revenir les légumes. Ajouter riz, mélanger. Creuser un puits, brouiller les œufs. Aromatiser soja.", desc: "Le classique asiatique fait maison." },

  // PLATS LÉGERS & SALADES-REPAS
  { id: 41, name: "Salade César poulet grillé", cat: "Salade", time: "25 min", img: "caesar,salad,chicken,grilled", ingredients: [["Blanc de poulet", "200g", 2.60], ["Salade romaine", "1", 1.20], ["Croûtons", "50g", 0.40], ["Parmesan", "40g", 0.80], ["Sauce César", "4 c.à.s", 0.60]], instructions: "Griller le poulet, trancher. Mélanger salade, sauce. Ajouter croûtons, parmesan, poulet.", desc: "La salade-repas américaine, fraîche et rassasiante." },
  { id: 42, name: "Wrap poulet crudités", cat: "Salade", time: "15 min", img: "wrap,chicken,vegetables,fresh", ingredients: [["Galettes de blé (paquet)", "2", 1.90], ["Blanc de poulet cuit", "150g", 1.95], ["Salade", "quelques feuilles", 0.30], ["Tomates", "2", 0.80], ["Concombre", "1/3", 0.20], ["Tzatziki", "2 c.à.s", 0.40]], instructions: "Garnir les galettes de tous les ingrédients. Rouler serré.", desc: "Déjeuner rapide et équilibré." },
  { id: 43, name: "Taboulé libanais", cat: "Salade", time: "20 min", img: "tabbouleh,lebanese,parsley", ingredients: [["Boulgour", "200g", 0.70], ["Tomates", "3", 1.20], ["Concombre", "1", 0.50], ["Persil plat", "2 bouquets", 1.00], ["Menthe", "1 bouquet", 0.60], ["Citron", "2", 0.80]], instructions: "Cuire boulgour. Hacher finement persil et menthe. Couper légumes. Mélanger. Assaisonner citron-huile.", desc: "Frais, herbacé, typiquement méditerranéen." },

  // LÉGUMINEUSES
  { id: 46, name: "Dal de lentilles corail", cat: "Plat végétarien", time: "25 min", img: "red,lentil,dal,indian", ingredients: [["Lentilles corail", "250g", 0.90], ["Tomates boîte", "400g", 0.90], ["Oignon", "1", 0.20], ["Ail", "2 gousses", 0.15], ["Cumin", "1 c.à.c", 0.10], ["Coriandre", "qq feuilles", 0.30]], instructions: "Faire revenir oignon, ail, cumin. Ajouter lentilles et tomates. Cuire 20 min. Parsemer coriandre.", desc: "Indien, végétalien, économique et délicieux." },
  { id: 47, name: "Chili con carne", cat: "Plat", time: "1h", img: "chili,con,carne,beans,beef", ingredients: [["Viande hachée bœuf", "400g", 4.40], ["Haricots rouges boîte", "400g", 0.90], ["Tomates concassées boîte", "400g", 0.90], ["Oignon", "1", 0.20], ["Piment", "1 c.à.c", 0.10], ["Cumin", "1 c.à.c", 0.10]], instructions: "Faire revenir viande et oignon. Ajouter épices, tomates, haricots. Mijoter 45 min.", desc: "Le plat tex-mex par excellence, épicé et nourrissant." },
  { id: 48, name: "Falafels sauce tahini", cat: "Plat végétarien", time: "30 min", img: "falafel,tahini,pita,chickpeas", ingredients: [["Pois chiches boîte", "400g", 0.90], ["Oignon", "1", 0.20], ["Ail", "2 gousses", 0.15], ["Coriandre", "1 botte", 0.50], ["Cumin", "1 c.à.c", 0.10], ["Farine", "2 c.à.s", 0.05]], instructions: "Mixer pois chiches avec épices et herbes. Façonner les falafels. Frire ou cuire au four. Servir avec tahini.", desc: "Street food libanais à faire à la maison." },
  { id: 49, name: "Cassoulet simplifié", cat: "Plat", time: "1h", img: "cassoulet,beans,sausage,duck", ingredients: [["Haricots blancs boîte", "800g", 1.80], ["Saucisses de Toulouse", "4", 4.50], ["Lardons", "150g", 2], ["Concentré tomates", "2 c.à.s", 0.30], ["Bouquet garni", "1", 0.30]], instructions: "Faire revenir saucisses et lardons. Ajouter haricots, tomate, bouquet garni. Mijoter 40 min. Gratiner.", desc: "Le cassoulet du Sud, réconfortant et généreux." },
  { id: 50, name: "Houmous maison pain pita", cat: "Entrée", time: "10 min", img: "hummus,pita,bread,chickpeas", ingredients: [["Pois chiches boîte", "400g", 0.90], ["Tahini", "2 c.à.s", 0.50], ["Citron", "1", 0.40], ["Ail", "1 gousse", 0.08], ["Huile d'olive", "2 c.à.s", 0.20], ["Pain pita", "4", 1.20]], instructions: "Mixer pois chiches avec tahini, citron, ail. Ajuster texture. Servir avec pain pita et huile d'olive.", desc: "Mezze oriental, simple et addictif." },

  // GRATINS & TARTES
  { id: 51, name: "Tarte aux poireaux chèvre", cat: "Plat végétarien", time: "50 min", img: "leek,goat,cheese,tart", ingredients: [["Pâte brisée", "1 rouleau", 2], ["Poireaux", "3", 1.80], ["Fromage de chèvre", "100g", 1.60], ["Œufs", "3", 0.90], ["Crème fraîche", "200ml", 1.2]], instructions: "Faire revenir poireaux. Battre œufs et crème. Foncer la pâte. Garnir poireaux, chèvre, migaine. Cuire 30 min.", desc: "Tarte du marché, douce et fondante." },
  { id: 52, name: "Gratin de courgettes chèvre", cat: "Plat végétarien", time: "40 min", img: "courgette,gratin,goat,cheese", ingredients: [["Courgettes", "3", 1.50], ["Fromage de chèvre", "150g", 2.40], ["Œufs", "2", 0.60], ["Crème fraîche", "150ml", 1.2], ["Basilic", "10 feuilles", 0.30]], instructions: "Faire revenir courgettes. Mélanger œufs-crème-chèvre. Assembler et enfourner 25 min.", desc: "Estival, léger et savoureux." },
  { id: 53, name: "Flammekueche (tarte flambée)", cat: "Plat", time: "30 min", img: "flammekueche,alsacian,onion,bacon", ingredients: [["Pâte fine", "1 rouleau", 2], ["Crème fraîche épaisse", "200g", 1.2], ["Oignons", "2", 0.40], ["Lardons", "150g", 2], ["Noix de muscade", "pincée", 0.05]], instructions: "Étaler pâte très fine. Étaler crème, parsemer oignons et lardons. Cuire 12 min à 240°C.", desc: "Alsacienne, croustillante et généreuse." },
  { id: 54, name: "Crumble de légumes", cat: "Plat végétarien", time: "45 min", img: "vegetable,crumble,savory", ingredients: [["Courgettes", "2", 1.00], ["Aubergines", "1", 0.80], ["Tomates", "2", 0.80], ["Farine", "80g", 0.10], ["Beurre", "60g", 0.30], ["Herbes Provence", "1 c.à.s", 0.10]], instructions: "Cuire légumes à la poêle. Disposer dans plat. Sabler farine-beurre-herbes. Parsemer. Cuire 25 min.", desc: "La version salée du crumble, surprenante et réussie." },

  // DESSERTS
  { id: 55, name: "Tarte aux pommes classique", cat: "Dessert", time: "1h", img: "apple,tart,french,classic", ingredients: [["Pâte brisée", "1 rouleau", 2], ["Pommes Golden", "4", 1.60], ["Compote pomme", "100g", 0.50], ["Sucre", "40g", 0.10], ["Beurre", "20g", 0.10], ["Cannelle", "1 c.à.c", 0.05]], instructions: "Foncer la pâte. Étaler compote. Disposer pommes en rosaces. Parsemer sucre-beurre. Cuire 40 min à 180°C.", desc: "La tarte familiale, simple et irrésistible." },
  { id: 56, name: "Mousse au chocolat", cat: "Dessert", time: "20 min", img: "chocolate,mousse,dark", ingredients: [["Chocolat noir 70%", "200g", 1.80], ["Œufs", "4", 1.20], ["Sucre", "40g", 0.10], ["Beurre", "30g", 0.15]], instructions: "Fondre chocolat-beurre. Séparer jaunes et blancs. Mélanger jaunes-chocolat-sucre. Incorporer blancs en neige délicatement. Réfrigérer 2h.", desc: "Légère et intense, la mousse parfaite." },
  { id: 57, name: "Crème brûlée", cat: "Dessert", time: "1h", img: "creme,brulee,vanilla,french", ingredients: [["Jaunes d'œufs", "4", 1.20], ["Crème liquide", "500ml", 1.2], ["Sucre", "80g", 0.20], ["Vanille", "1 gousse", 1.20]], instructions: "Mélanger jaunes, sucre, crème et vanille. Verser en ramequins. Cuire bain-marie 45 min à 150°C. Caraméliser au chalumeau.", desc: "Le dessert gastronomique, réalisable à la maison." },
  { id: 58, name: "Fondant au chocolat coulant", cat: "Dessert", time: "20 min", img: "chocolate,fondant,molten,lava", ingredients: [["Chocolat noir", "150g", 1.35], ["Beurre", "80g", 0.40], ["Œufs", "2", 0.60], ["Jaunes d'œufs", "2", 0.60], ["Sucre", "50g", 0.13], ["Farine", "20g", 0.03]], instructions: "Fondre chocolat-beurre. Battre œufs-sucre. Mélanger tout. Remplir ramequins. Cuire 10 min à 200°C.", desc: "Le gâteau au cœur liquide, toujours impressionnant." },
  { id: 59, name: "Clafoutis aux cerises", cat: "Dessert", time: "45 min", img: "clafoutis,cherries,french", ingredients: [["Cerises fraîches", "400g", 2.40], ["Œufs", "3", 0.90], ["Lait", "300ml", 0.33], ["Farine", "100g", 0.15], ["Sucre", "80g", 0.20], ["Beurre", "20g", 0.10]], instructions: "Dénoyauter cerises. Battre œufs, sucre, farine, lait. Verser sur cerises dans plat beurré. Cuire 35 min à 180°C.", desc: "Le dessert de saison, moelleux et fruité." },
  { id: 60, name: "Panna cotta coulis framboise", cat: "Dessert", time: "15 min", img: "panna,cotta,raspberry,coulis", ingredients: [["Crème liquide", "400ml", 1.20], ["Sucre", "50g", 0.13], ["Gélatine", "3 feuilles", 0.30], ["Vanille", "1 gousse", 1.20], ["Framboises", "200g", 1.60]], instructions: "Chauffer crème avec sucre et vanille. Incorporer gélatine ramollie. Verser dans verrines. Réfrigérer 3h. Servir avec coulis.", desc: "Italienne, élégante et légère." },
  { id: 61, name: "Île flottante", cat: "Dessert", time: "30 min", img: "floating,island,dessert,caramel", ingredients: [["Œufs", "4", 1.20], ["Lait", "500ml", 0.55], ["Sucre", "120g", 0.30], ["Vanille", "1 gousse", 1.20], ["Amandes effilées", "30g", 0.60]], instructions: "Faire crème anglaise vanillée. Monter blancs en neige, pocher dans lait. Préparer caramel. Dresser.", desc: "Le grand dessert classique de la pâtisserie française." },
  { id: 62, name: "Tarte au citron meringuée", cat: "Dessert", time: "1h15", img: "lemon,tart,meringue,french", ingredients: [["Pâte sablée", "1 rouleau", 2], ["Citrons", "3", 1.20], ["Œufs", "3", 0.90], ["Beurre", "80g", 0.40], ["Sucre", "120g", 0.30], ["Blancs d'œufs", "2", 0.40]], instructions: "Cuire pâte à blanc. Faire crème citron. Garnir. Faire meringue italienne. Bruler au chalumeau.", desc: "Acidulée et sucrée, l'équilibre parfait." },
  { id: 63, name: "Pain perdu caramel beurre salé", cat: "Dessert", time: "15 min", img: "french,toast,salted,caramel", ingredients: [["Pain rassis", "4 tranches", 0.20], ["Œufs", "2", 0.60], ["Lait", "100ml", 0.11], ["Sucre", "30g", 0.08], ["Beurre demi-sel", "30g", 0.18], ["Caramel beurre salé", "3 c.à.s", 0.60]], instructions: "Tremper pain dans mélange œufs-lait. Cuire au beurre. Napper de caramel beurre salé.", desc: "Anti-gaspi et délicieux, vite fait bien fait." },
  { id: 64, name: "Compote de pommes maison", cat: "Dessert", time: "20 min", img: "apple,compote,homemade,cinnamon", ingredients: [["Pommes", "5", 2.00], ["Citron", "1/2", 0.20], ["Sucre", "30g", 0.08], ["Cannelle", "1 bâton", 0.20], ["Eau", "3 c.à.s", 0]], instructions: "Éplucher et couper les pommes. Cuire avec sucre, citron et cannelle 15 min. Mixer selon texture souhaitée.", desc: "Simple, saine, douce : la compote maison." },
  { id: 65, name: "Cookies chocolat noix", cat: "Dessert", time: "25 min", img: "cookies,chocolate,nuts,homemade", ingredients: [["Farine", "200g", 0.30], ["Beurre", "125g", 0.63], ["Sucre brun", "150g", 0.40], ["Œufs", "1", 0.30], ["Pépites chocolat", "100g", 1.00], ["Noix", "50g", 0.80]], instructions: "Battre beurre-sucre. Ajouter œuf, farine, pépites, noix. Former des boules. Cuire 12 min à 180°C.", desc: "Crunchy dehors, fondant dedans." },

  // SOUPES & VELOUTÉS
  { id: 66, name: "Soupe de tomates fraîches", cat: "Entrée", time: "30 min", img: "tomato,soup,fresh,basil", ingredients: [["Tomates mûres", "800g", 2.40], ["Oignon", "1", 0.20], ["Ail", "2 gousses", 0.15], ["Basilic frais", "10 feuilles", 0.40], ["Crème fraîche", "100ml", 1.2]], instructions: "Faire revenir oignon, ail. Ajouter tomates, cuire 20 min. Mixer. Ajouter crème et basilic.", desc: "La soupe de la belle saison, douce et parfumée." },
  { id: 67, name: "Velouté de carottes gingembre", cat: "Entrée", time: "30 min", img: "carrot,ginger,soup,cream", ingredients: [["Carottes", "600g", 1.20], ["Gingembre frais", "2cm", 0.30], ["Oignon", "1", 0.20], ["Crème de coco", "100ml", 0.60], ["Bouillon légumes", "600ml", 0.36]], instructions: "Cuire carottes, oignon, gingembre dans bouillon 20 min. Mixer. Ajouter crème de coco.", desc: "Doux, épicé, réconfortant." },
  { id: 68, name: "Soupe de pois cassés au jambon", cat: "Plat", time: "1h", img: "split,pea,soup,ham,french", ingredients: [["Pois cassés", "300g", 1.05], ["Jambon fumé", "150g", 2.2], ["Carottes", "2", 0.40], ["Oignon", "1", 0.20], ["Laurier", "2 feuilles", 0.05]], instructions: "Faire revenir oignon. Ajouter pois cassés, légumes, bouillon. Cuire 45 min. Ajouter jambon coupé.", desc: "Épaisse et nourrissante, soupe d'hiver par excellence." },
  { id: 69, name: "Velouté de céleri aux noisettes", cat: "Entrée", time: "35 min", img: "celery,soup,hazelnuts,cream", ingredients: [["Céleri-rave", "500g", 1.50], ["Oignon", "1", 0.20], ["Noisettes torréfiées", "30g", 0.60], ["Crème fraîche", "100ml", 1.2], ["Bouillon poulet", "500ml", 0.30]], instructions: "Cuire céleri et oignon dans bouillon 25 min. Mixer avec crème. Garnir de noisettes concassées.", desc: "Délicat et original, une belle entrée d'automne." },
  { id: 70, name: "Potage Parmentier", cat: "Entrée", time: "30 min", img: "potato,leek,soup,french", ingredients: [["Pommes de terre", "500g", 1.00], ["Poireaux", "2", 1.20], ["Oignon", "1", 0.20], ["Crème fraîche", "100ml", 1.2], ["Bouillon poulet", "800ml", 0.48]], instructions: "Cuire pommes de terre, poireaux, oignon dans bouillon 20 min. Mixer. Ajouter crème.", desc: "La soupe du soir, douce et réconfortante." },

  // SANDWICHS & SNACKS
  { id: 71, name: "Croque-monsieur maison", cat: "Snack", time: "15 min", img: "croque,monsieur,french,toast,ham", ingredients: [["Pain de mie", "4 tranches", 0.40], ["Jambon blanc", "2 tranches", 2.2], ["Gruyère râpé", "60g", 2.3], ["Beurre", "20g", 0.10], ["Béchamel", "2 c.à.s", 0.20]], instructions: "Badigeonner béchamel sur 2 tranches. Ajouter jambon et fromage. Fermer et beurrer l'extérieur. Griller à la poêle.", desc: "Le sandwich chaud français, croustillant et fondant." },
  { id: 73, name: "Pannini mozzarella pesto", cat: "Snack", time: "10 min", img: "panini,mozzarella,pesto,grilled", ingredients: [["Ciabatta", "2", 1.20], ["Mozzarella", "125g", 1.20], ["Pesto", "2 c.à.s", 0.50], ["Tomates séchées", "4", 0.40], ["Roquette", "30g", 0.40]], instructions: "Ouvrir ciabatta. Tartiner pesto. Ajouter mozzarella, tomates séchées. Griller à la machine ou à la poêle.", desc: "Italien, chaud, fondant." },

  // PLATS DU MONDE
  { id: 74, name: "Gyozas poêlés sauce ponzu", cat: "Plat", time: "30 min", img: "gyoza,dumpling,japanese,pan,fried", ingredients: [["Feuilles gyoza", "20", 1.50], ["Porc haché", "200g", 2.40], ["Chou", "100g", 0.30], ["Ail", "1 gousse", 0.08], ["Sauce soja", "2 c.à.s", 0.15], ["Sauce ponzu", "3 c.à.s", 0.40]], instructions: "Mélanger porc, chou, ail. Farcir les feuilles. Saisir à l'huile puis ajouter eau. Couvrir 5 min. Servir avec ponzu.", desc: "Les raviolis japonais dorés et croustillants." },
  { id: 75, name: "Tajine poulet citron confit olives", cat: "Plat", time: "1h30", img: "tagine,chicken,lemon,olives", ingredients: [["Poulet morceaux", "800g", 5.60], ["Citron confit", "1", 0.80], ["Olives vertes", "80g", 0.80], ["Oignon", "1", 0.20], ["Ras el hanout", "2 c.à.s", 0.30], ["Coriandre", "1 bouquet", 0.50]], instructions: "Faire revenir poulet et oignon avec épices. Ajouter citron et olives. Mijoter 1h15. Parsemer coriandre.", desc: "Marocain, parfumé, fondant." },
  { id: 77, name: "Shakshuka", cat: "Plat végétarien", time: "25 min", img: "shakshuka,eggs,tomato,spices", ingredients: [["Tomates boîte", "400g", 0.90], ["Poivrons", "2", 1.60], ["Œufs", "4", 1.20], ["Oignon", "1", 0.20], ["Cumin", "1 c.à.c", 0.10], ["Paprika fumé", "1 c.à.c", 0.10]], instructions: "Faire revenir oignon et poivrons. Ajouter tomates et épices, cuire 10 min. Casser les œufs dedans. Couvrir 5 min.", desc: "Israélien, simple, délicieux à tout moment." },
  { id: 78, name: "Adobo poulet philippin", cat: "Plat", time: "45 min", img: "chicken,adobo,philippine,soy", ingredients: [["Poulet morceaux", "700g", 4.90], ["Sauce soja", "80ml", 0.60], ["Vinaigre de riz", "80ml", 0.40], ["Ail", "6 gousses", 0.40], ["Laurier", "3 feuilles", 0.10], ["Poivre noir", "1 c.à.c", 0.05]], instructions: "Mariner poulet dans soja-vinaigre-ail. Faire revenir. Ajouter marinade et laurier. Mijoter 30 min.", desc: "Acide, salé, umami : le plat national philippin." },
  { id: 79, name: "Bœuf façon stroganoff", cat: "Plat", time: "30 min", img: "beef,stroganoff,cream,mushrooms", ingredients: [["Filet de bœuf", "300g", 14.00], ["Champignons", "200g", 1.60], ["Crème fraîche", "200ml", 1.2], ["Oignon", "1", 0.20], ["Paprika", "1 c.à.c", 0.05], ["Moutarde", "1 c.à.c", 0.10]], instructions: "Saisir le bœuf en lamelles. Faire revenir oignon et champignons. Ajouter crème, paprika, moutarde. Mélanger et réchauffer.", desc: "Russe, crémeux, rapide et délicieux." },
  { id: 80, name: "Quesadillas poulet cheddar", cat: "Plat", time: "15 min", img: "quesadilla,chicken,cheese,mexican", ingredients: [["Tortillas de blé (paquet)", "4", 1.90], ["Poulet cuit", "200g", 2.60], ["Cheddar râpé", "100g", 2.3], ["Poivron", "1", 0.80], ["Oignon rouge", "1/2", 0.15]], instructions: "Garnir une tortilla de poulet, fromage, légumes. Couvrir d'une seconde tortilla. Griller 3 min chaque côté.", desc: "Mexicain, rapide et irrésistible." },

  // ACCOMPAGNEMENTS & EXTRAS
  { id: 81, name: "Purée de pommes de terre maison", cat: "Accompagnement", time: "25 min", img: "mashed,potato,butter,cream", ingredients: [["Pommes de terre", "800g", 1.60], ["Beurre", "80g", 0.40], ["Lait chaud", "150ml", 0.17], ["Sel", "", 0.01], ["Noix de muscade", "pincée", 0.05]], instructions: "Cuire pommes de terre. Écraser avec beurre. Ajouter lait chaud progressivement. Assaisonner.", desc: "La purée parfaite, onctueuse et légère." },
  { id: 82, name: "Sauce béarnaise", cat: "Accompagnement", time: "20 min", img: "bearnaise,sauce,french,egg", ingredients: [["Jaunes d'œufs", "3", 0.90], ["Beurre clarifié", "200g", 1.00], ["Vinaigre de vin", "3 c.à.s", 0.15], ["Echalotes", "2", 0.30], ["Estragon", "1 bouquet", 0.60]], instructions: "Réduire vinaigre-échalotes. Monter au bain-marie avec jaunes. Incorporer beurre clarifier en filet. Ajouter estragon.", desc: "La sauce classique pour les grillades." },
  { id: 83, name: "Taboulé marocain", cat: "Accompagnement", time: "20 min", img: "moroccan,couscous,salad,mint", ingredients: [["Couscous fin", "200g", 0.70], ["Tomates", "3", 1.20], ["Concombre", "1", 0.50], ["Menthe", "1 bouquet", 0.60], ["Persil", "1 bouquet", 0.50], ["Citron", "2", 0.80]], instructions: "Gonfler couscous à l'eau bouillante. Refroidir. Mélanger légumes en dés, herbes, citron, huile.", desc: "Version couscous du taboulé, généreuse et fraîche." },
  { id: 84, name: "Galettes de pommes de terre rösti", cat: "Accompagnement", time: "20 min", img: "rosti,potato,swiss,crispy", ingredients: [["Pommes de terre", "600g", 1.20], ["Beurre", "40g", 0.20], ["Oignon", "1", 0.20], ["Sel, poivre", "", 0.02]], instructions: "Râper pommes de terre crue. Presser pour ôter eau. Mélanger oignon. Former galettes. Cuire au beurre 5 min chaque côté.", desc: "Croustillant suisse, irrésistible avec une salade." },
  { id: 85, name: "Tomates confites à l'huile", cat: "Accompagnement", time: "2h", img: "confit,tomatoes,olive,oil,thyme", ingredients: [["Tomates cerises", "400g", 2.00], ["Ail", "4 gousses", 0.25], ["Thym", "4 branches", 0.20], ["Huile d'olive", "200ml", 2.00], ["Sel, sucre", "", 0.05]], instructions: "Couper tomates en deux. Disposer dans plat. Arroser huile, ajouter ail et thym. Cuire 2h à 100°C.", desc: "Concentrées et dorées, elles subliment tout." },

  // SNACKS & GOÛTER
  { id: 86, name: "Cake salé jambon olives", cat: "Snack", time: "55 min", img: "savory,cake,ham,olives,cheese", ingredients: [["Farine", "200g", 0.30], ["Œufs", "3", 0.90], ["Gruyère râpé", "100g", 2.3], ["Jambon", "150g", 2.2], ["Olives", "80g", 0.80], ["Huile", "100ml", 0.50]], instructions: "Mélanger farine, œufs, huile, fromage. Ajouter jambon coupé et olives. Cuire 45 min à 180°C.", desc: "Le cake de l'apéro, moelleux et garni." },
  { id: 87, name: "Muffins aux myrtilles", cat: "Goûter", time: "30 min", img: "blueberry,muffins,homemade", ingredients: [["Farine", "220g", 0.33], ["Myrtilles", "150g", 1.80], ["Yaourt", "1", 0.40], ["Œufs", "1", 0.30], ["Sucre", "80g", 0.20], ["Lait", "100ml", 0.11]], instructions: "Mélanger ingrédients secs et humides séparément. Incorporer délicatement les myrtilles. Cuire 20 min à 190°C.", desc: "Moelleux et fruités, parfaits au petit-déj." },
  { id: 88, name: "Banana bread", cat: "Goûter", time: "1h", img: "banana,bread,homemade,walnut", ingredients: [["Bananes mûres", "3", 0.90], ["Farine", "200g", 0.30], ["Beurre", "80g", 0.40], ["Sucre brun", "100g", 0.27], ["Œufs", "2", 0.60], ["Noix", "50g", 0.80]], instructions: "Écraser bananes. Mélanger avec beurre fondu, sucre, œufs. Incorporer farine et noix. Cuire 55 min à 175°C.", desc: "Anti-gaspi et délicieux, le gâteau des bananes trop mûres." },
  { id: 89, name: "Financiers aux amandes", cat: "Goûter", time: "25 min", img: "financier,almond,french,cake", ingredients: [["Poudre d'amandes", "100g", 1.60], ["Blancs d'œufs", "3", 0.60], ["Beurre noisette", "80g", 0.40], ["Sucre glace", "120g", 0.30], ["Farine", "40g", 0.06]], instructions: "Faire beurre noisette. Mélanger tous les ingrédients. Remplir moules. Cuire 12 min à 200°C.", desc: "Le petit gâteau de la pâtisserie française, moelleux et doré." },
  { id: 90, name: "Madeleines au miel citron", cat: "Goûter", time: "30 min", img: "madeleines,honey,lemon,french", ingredients: [["Farine", "150g", 0.23], ["Beurre", "100g", 0.50], ["Miel", "2 c.à.s", 0.30], ["Citron", "1 zeste", 0.40], ["Œufs", "2", 0.60], ["Sucre", "80g", 0.20]], instructions: "Mélanger tous les ingrédients. Réfrigérer 1h. Remplir moules. Cuire 12 min à 210°C.", desc: "Moelleuses et parfumées, les madeleines de Proust." },

  // PLATS FESTIFS & SPÉCIAUX
  { id: 91, name: "Côte de bœuf sauce chimichurri", cat: "Plat", time: "30 min", img: "rib,steak,chimichurri,grill", ingredients: [["Côte de bœuf", "800g", 24.00], ["Persil plat", "1 bouquet", 0.50], ["Ail", "4 gousses", 0.25], ["Huile d'olive", "80ml", 0.80], ["Vinaigre rouge", "2 c.à.s", 0.10], ["Piment", "1 c.à.c", 0.10]], instructions: "Tempérer la viande 1h. Griller 5 min chaque côté. Reposer 10 min. Mixer chimichurri. Servir tranché.", desc: "La pièce maîtresse pour les grandes occasions." },
  { id: 93, name: "Foie gras poêlé pomme caramélisée", cat: "Entrée", time: "15 min", img: "foie,gras,apple,caramel,pan,fried", ingredients: [["Escalopes foie gras", "2 × 80g", 12.00], ["Pommes", "2", 0.80], ["Miel", "2 c.à.s", 0.30], ["Beurre", "20g", 0.10], ["Fleur de sel", "pincée", 0.05]], instructions: "Caraméliser pommes au beurre-miel. Poêler foie gras 1 min chaque côté. Fleur de sel, déglacer.", desc: "Le luxe français en 15 minutes." },
  { id: 94, name: "Magret de canard aux cerises", cat: "Plat", time: "25 min", img: "duck,magret,cherries,sauce", ingredients: [["Magret de canard", "2", 15.00], ["Cerises", "200g", 1.20], ["Vinaigre balsamique", "3 c.à.s", 0.45], ["Sucre", "30g", 0.08], ["Fond de veau", "200ml", 0.60]], instructions: "Quadriller le magret côté gras. Cuire 7 min gras, 4 min chair. Reposer. Faire sauce cerises-balsamique.", desc: "Le magret parfait, rosé et juteux." },
  { id: 95, name: "Soufflé au fromage", cat: "Entrée", time: "35 min", img: "souffle,cheese,gruyere,french", ingredients: [["Gruyère râpé", "100g", 2.3], ["Œufs", "4", 1.20], ["Beurre", "40g", 0.20], ["Farine", "40g", 0.06], ["Lait", "300ml", 0.33], ["Noix de muscade", "pincée", 0.05]], instructions: "Faire béchamel. Ajouter jaunes et fromage. Monter blancs. Incorporer délicatement. Cuire 25 min à 200°C sans ouvrir.", desc: "Le défi culinaire, impressionnant et délicieux." },

  // RECETTES ÉCONOMIQUES MALIN
  { id: 96, name: "Frittata de légumes", cat: "Plat végétarien", time: "20 min", img: "frittata,italian,vegetables,eggs", ingredients: [["Œufs", "6", 1.80], ["Courgettes", "2", 1.00], ["Oignon", "1", 0.20], ["Parmesan", "40g", 0.80], ["Huile d'olive", "2 c.à.s", 0.20]], instructions: "Faire revenir légumes. Battre œufs avec parmesan. Verser sur légumes. Cuire 5 min à la poêle puis 10 min au four.", desc: "L'omelette italienne épaisse, repas complet." },
  { id: 97, name: "Soupe de pain panzanella", cat: "Entrée", time: "15 min", img: "bread,tomato,panzanella,italian", ingredients: [["Pain rassis", "200g", 0.30], ["Tomates mûres", "4", 1.60], ["Oignon rouge", "1", 0.30], ["Basilic", "10 feuilles", 0.40], ["Huile d'olive", "4 c.à.s", 0.40], ["Vinaigre", "1 c.à.s", 0.05]], instructions: "Tremper pain dans eau. Essorer. Mélanger avec tomates, oignon, basilic, huile et vinaigre.", desc: "Anti-gaspi toscan, frais et savoureux." },
  { id: 98, name: "Riz au lait vanille", cat: "Dessert", time: "40 min", img: "rice,pudding,vanilla,milk,cream", ingredients: [["Riz rond", "150g", 0.45], ["Lait", "800ml", 0.88], ["Sucre", "60g", 0.15], ["Vanille", "1 gousse", 1.20], ["Crème fraîche", "100ml", 1.2]], instructions: "Chauffer lait avec vanille. Ajouter riz, cuire 35 min à feu doux en remuant. Sucrer. Servir tiède ou froid.", desc: "Le dessert de l'enfance, crémeux et réconfortant." },
  { id: 99, name: "Gratin de pâtes bolognaise", cat: "Plat", time: "50 min", img: "pasta,bake,bolognese,cheese,gratin", ingredients: [["Pâtes courtes", "300g", 0.75], ["Viande hachée", "300g", 3.30], ["Tomates boîte", "400g", 0.90], ["Béchamel", "300ml", 0.60], ["Gruyère", "80g", 2.30]], instructions: "Cuire pâtes. Faire bolognaise. Mélanger tout. Verser béchamel, parsemer gruyère. Gratiner 20 min.", desc: "Les pâtes en gratin, encore meilleures réchauffées." },
  { id: 100, name: "Brioche perdue aux fruits de saison", cat: "Dessert", time: "20 min", img: "brioche,french,toast,seasonal,fruit", ingredients: [["Brioche tranchée", "6 tranches", 1.80], ["Œufs", "3", 0.90], ["Lait", "150ml", 0.17], ["Sucre vanillé", "1 sachet", 0.20], ["Beurre", "30g", 0.15], ["Fruits de saison", "200g", 1.20]], instructions: "Tremper brioche dans mélange œufs-lait-sucre. Cuire au beurre. Servir avec fruits coupés et sucre glace.", desc: "Le dessert de bistrot, rapide et élégant." }
];
